name: Zephyrus
version: 1.0
api-version: 1.16
main: me.zeph.zephyrus.Zephyrus
depend: [ProjectKorra]
authors: [Zeph]
description: Improves airbending
loadbefore: [PKConfigApi]
zephyrus.player:
    default: true
    description: Access to zephyrus abilities.
    children:
      bending.ability.AirBall: true
      bending.ability.AirStrike: true
      bending.ability.AirPropulsion: true
      bending.ability.SpiritualProjection: true
